// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHcktxOEnDNMlkEeg4AFQkuzYiGkFDlM',
    appId: '1:650960716861:web:83bd37aee58f08c0b25654',
    messagingSenderId: '650960716861',
    projectId: 'addies-83af7',
    authDomain: 'addies-83af7.firebaseapp.com',
    databaseURL: 'https://addies-83af7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'addies-83af7.appspot.com',
    measurementId: 'G-L6D7E0V3QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzgswzH-ItdNHb59vcAN9CSB-h42BDMGk',
    appId: '1:650960716861:android:b3d43a702c8a9723b25654',
    messagingSenderId: '650960716861',
    projectId: 'addies-83af7',
    databaseURL: 'https://addies-83af7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'addies-83af7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYixSuK_4sHF1VHaJKM_u_Kt6lRCa8QbE',
    appId: '1:650960716861:ios:e02c05591528b3e1b25654',
    messagingSenderId: '650960716861',
    projectId: 'addies-83af7',
    databaseURL: 'https://addies-83af7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'addies-83af7.appspot.com',
    androidClientId: '650960716861-6akkkb31375h4vcckh4leml8arfttsdb.apps.googleusercontent.com',
    iosClientId: '650960716861-psgkmo91a3qsr725tntkb8h36l1u0uco.apps.googleusercontent.com',
    iosBundleId: 'com.example.addiesShamiyana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYixSuK_4sHF1VHaJKM_u_Kt6lRCa8QbE',
    appId: '1:650960716861:ios:e02c05591528b3e1b25654',
    messagingSenderId: '650960716861',
    projectId: 'addies-83af7',
    databaseURL: 'https://addies-83af7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'addies-83af7.appspot.com',
    androidClientId: '650960716861-6akkkb31375h4vcckh4leml8arfttsdb.apps.googleusercontent.com',
    iosClientId: '650960716861-psgkmo91a3qsr725tntkb8h36l1u0uco.apps.googleusercontent.com',
    iosBundleId: 'com.example.addiesShamiyana',
  );
}
